dist: xenial
language: csharp
sudo: required
mono: none
dotnet: 2.1

services:
  - mongodb
  - docker

branches:
  except:
    - /^v[0-9]/

if: tag IS blank

before_install:
  - sed -i -e "s/\"build\":\s[0-9]*/\"build\":"' '"$TRAVIS_BUILD_NUMBER/" component.json

install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update
  - sudo apt-get install -y powershell

script: 
  - ./build.ps1
  # - ./test.ps1
  - ./package.ps1
  - ./tag.ps1
  - ./publish.ps1
  # - ./release.ps1

after_script:
  - ./clean.ps1